#! /bin/sh 

pgrep -x sxhkd > /dev/null || sxhkd &
#sxhkd &

#Swallow
pgrep ~/bin/wm/bspswallow || ~/bin/wm/bspswallow &

~/.config/polybar/launch.sh  &

bspc monitor -d I II III IV V VI

bspc config border_width          1
bspc config window_gap            10
bspc config normal_border_color  '#000000'
bspc config focused_border_color "#FFFFFF"
bspc config presel_feedback_color "#EDE0CE"

bspc config directional_focus_tightness low

bspc config split_ratio           0.52 
bspc config borderless_monocle    true 
bspc config gapless_monocle       true 
bspc config single_monocle        false
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on 
bspc rule -a Chromium desktop='^1' 
bspc rule -a Brave desktop='^1' 
bspc rule -a Thunderbird desktop='^6' 
bspc rule -a Dino desktop='^6' 
bspc rule -a KeePassXC desktop='^6' 
bspc rule -a mplayer2 state=floating 
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on 
bspc rule -a Screenkey manage=off 

bspc rule -a Floating state=floating

~/bin/autostart &
