#! /bin/sh 
#pgrep -x sxhkd > /dev/null || sxhkd &
pkill sxhkd && sxhkd &

#Swallow
pgrep ~/bin/bspswallow || ~/bin/bspswallow &

~/bin/autostart
~/.config/polybar/launch.sh  &

bspc monitor -d web code term misc mail 

bspc config border_width          2
bspc config window_gap            13

bspc config split_ratio           0.52 
bspc config borderless_monocle    true 
bspc config gapless_monocle       true 
bspc config focus_follows_pointer true


# bspc rule -a Gimp desktop='^8' state=floating follow=on 
bspc rule -a Chromium desktop='^web' 
bspc rule -a Brave desktop='^1' 
bspc rule -a Thunderbird desktop='^5' 
bspc rule -a KeePassXC desktop='^5' 
bspc rule -a mplayer2 state=floating 
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on 
bspc rule -a Screenkey manage=off 


