#! /bin/sh 

~/bin/autostart
#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

#Swallow
pgrep ~/bin/bspswallow || ~/bin/bspswallow &

~/.config/polybar/launch.sh  &

bspc monitor -d web code term misc tmp mail 

bspc config border_width          2
bspc config window_gap            13

bspc config split_ratio           0.52 
bspc config borderless_monocle    true 
bspc config gapless_monocle       true 
bspc config focus_follows_pointer true


# bspc rule -a Gimp desktop='^8' state=floating follow=on 
bspc rule -a Chromium desktop='^web' 
bspc rule -a Brave desktop='^1' 
bspc rule -a Thunderbird desktop='^6' 
bspc rule -a KeePassXC desktop='^5' 
bspc rule -a mplayer2 state=floating 
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on 
bspc rule -a Screenkey manage=off 

if [[ $my_laptop_external_monitor = *connected* ]]; then
    echo "one screen"
else
bspc rule -a Brave desktop='^4' 
bspc rule -a Thunderbird desktop='^9' 
bspc rule -a KeePassXC desktop='^9' 
fi
